In [1]:
# Actual Value of Products sold 
Router1_data = [906, 941, 663, 769, 3565, 1020, 1670, 38, 2141]

#Prediction data using various methods

q1_pred = [
    {
        'type': 'Demand Planning',
        'accuracy': 0.71,
        'bias': -0.292
    },
    {
        'type': 'Marketing',
        'accuracy': 0.57,
        'bias': -0.427
    },
    {
        'type': 'ML',
        'accuracy': 0.50,
        'bias': -0.496
    }
]
q2_pred = [
    {
        'type': 'Demand Planning',
        'accuracy': 0,
        'bias': 58.684
    },
    {
        'type': 'Marketing',
        'accuracy': 0,
        'bias': 80.658 
    },
    {
        'type': 'ML',
        'accuracy': 0,
        'bias': 47.053
    }
]
q3_pred = [
    {
        'type': 'Demand Planning',
        'accuracy': 0.98,
        'bias': 0.025
    },
    {
        'type': 'Marketing',
        'accuracy': 0.72,
        'bias': 0.281
    },
    {
        'type': 'ML',
        'accuracy': 0.98,
        'bias': 0.016
    }
]

# Quarter 4 Prediction

q4_pred = {
    1716, 1716, 1948
}

In [2]:
# Finding actual prediction value for the methods

for type in q1_pred:
    type['prediction'] = ((type['bias'] / 100) * Router1_data[-3]) + Router1_data[-3] 
for type in q2_pred:
    type['prediction'] = ((type['bias'] / 100) * Router1_data[-2]) + Router1_data[-2] 
for type in q3_pred:
    type['prediction'] = ((type['bias'] / 100) * Router1_data[-1]) + Router1_data[-1] 
print(q1_pred)
print(q2_pred)
print(q3_pred)

[{'type': 'Demand Planning', 'accuracy': 0.71, 'bias': -0.292, 'prediction': 1665.1236}, {'type': 'Marketing', 'accuracy': 0.57, 'bias': -0.427, 'prediction': 1662.8691}, {'type': 'ML', 'accuracy': 0.5, 'bias': -0.496, 'prediction': 1661.7168}]
[{'type': 'Demand Planning', 'accuracy': 0, 'bias': 58.684, 'prediction': 60.29992}, {'type': 'Marketing', 'accuracy': 0, 'bias': 80.658, 'prediction': 68.65003999999999}, {'type': 'ML', 'accuracy': 0, 'bias': 47.053, 'prediction': 55.88014}]
[{'type': 'Demand Planning', 'accuracy': 0.98, 'bias': 0.025, 'prediction': 2141.53525}, {'type': 'Marketing', 'accuracy': 0.72, 'bias': 0.281, 'prediction': 2147.01621}, {'type': 'ML', 'accuracy': 0.98, 'bias': 0.016, 'prediction': 2141.34256}]

In [3]:
import pandas as pd
from prophet import Prophet

Importing plotly failed. Interactive plots will not work.

In [6]:
df = pd.read_csv('forcast.csv')
# df = df.T
df = df.T.reset_index()
# df = df.set_index(df.iloc[0])
df = df.drop(df.index[0])
df = df.drop(df.index[11])
df

,index,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
1,2020-10-01,NaN,87173.0,NaN,NaN,NaN,13432.0,28585.0,115709.0,NaN,...,NaN,65048.0,NaN,6073.0,1208.0,4.0,6187.0,NaN,NaN,28279.0
2,2021-01-01,NaN,102849.0,NaN,NaN,NaN,12463.0,19686.0,98337.0,NaN,...,NaN,67810.0,NaN,5459.0,963.0,-4.0,5301.0,NaN,NaN,22704.0
3,2021-04-01,NaN,126375.0,NaN,NaN,NaN,13452.0,44724.0,147681.0,NaN,...,NaN,90928.0,NaN,6736.0,1698.0,36.0,7172.0,NaN,NaN,24098.0
4,2021-07-01,906.0,128629.0,3651.0,NaN,NaN,14581.0,37781.0,185327.0,177.0,...,NaN,148547.0,NaN,12213.0,1833.0,305.0,7582.0,NaN,NaN,31461.0
5,2021-10-01,941.0,179125.0,10409.0,NaN,NaN,15831.0,31905.0,194170.0,270.0,...,NaN,228945.0,NaN,13883.0,2423.0,1093.0,10964.0,NaN,NaN,47009.0
6,2022-01-01,663.0,138750.0,10575.0,NaN,NaN,13864.0,37888.0,220386.0,850.0,...,NaN,204184.0,NaN,27045.0,2602.0,2360.0,11501.0,NaN,NaN,35145.0
7,2022-04-01,769.0,208760.0,17934.0,9576.0,NaN,15012.0,32689.0,204604.0,2717.0,...,222.0,245453.0,15.0,15162.0,2341.0,4317.0,14980.0,NaN,NaN,45978.0
8,2022-07-01,3565.0,116126.0,15104.0,46029.0,NaN,11349.0,30442.0,194538.0,3833.0,...,1549.0,245803.0,108.0,13855.0,1830.0,4343.0,9158.0,NaN,NaN,34518.0
9,2022-10-01,1020,150803,15525,109452,26769,10422,27028,185160,4279,...,4619,136283,1972,12351,1567,4094,11601,13260,1227,40605
10,2023-01-01,1670,82163,6938,54955,33670,8726,21246,147284,6089,...,4764,76020,2427,8933,1210,2756,3788,21667,24186,26925
11,2023-04-01,38,82408,9595,60478,74853,10185,21149,136997,8063,...,5015,51586,2841,5909,1659,3126,5338,30498,7680,23635

In [10]:
router1 = pd.DataFrame()
router1 = df[['index', 0]].rename(columns={'index': 'ds', 0: 'y'})
router1

            ds       y
1   2020-10-01     NaN
2   2021-01-01     NaN
3   2021-04-01     NaN
4   2021-07-01   906.0
5   2021-10-01   941.0
6   2022-01-01   663.0
7   2022-04-01   769.0
8   2022-07-01  3565.0
9   2022-10-01    1020
10  2023-01-01    1670
11  2023-04-01      38

In [9]:
for i in range(0,20):
    model = Prophet(weekly_seasonality=False, yearly_seasonality=False)
    model.add_seasonality(name='quarterly', period=4, fourier_order=5)
    router1 = pd.DataFrame()
    router1 = df[['index', i]].rename(columns={'index': 'ds', i: 'y'})
    model.fit(router1)
    future = model.make_future_dataframe(periods=1, freq='Q')  
    forecast = model.predict(future)
    print("Product:", i)
    forecast.to_csv('forcasts/product_'+str(i))

10:44:49 - cmdstanpy - INFO - Chain [1] start processing
10:44:49 - cmdstanpy - INFO - Chain [1] done processing

10:44:49 - cmdstanpy - INFO - Chain [1] start processing
10:44:49 - cmdstanpy - INFO - Chain [1] done processing
10:44:49 - cmdstanpy - INFO - Chain [1] start processing
10:44:49 - cmdstanpy - INFO - Chain [1] done processing
10:44:49 - cmdstanpy - INFO - Chain [1] start processing

Product: 0
0    1364.841355
1     836.690901
2     308.540447
3     768.947472
4    2612.263941
5    2084.113488
6    1555.963035
7      33.585511
8     522.625193
Name: yhat, dtype: float64
Product: 1
0      96388.667200
1      94852.326273
2     125715.534657
3     150366.359885
4     148830.019014
5     147293.678192
6     208776.341776
7     118100.627567
8     116564.286835
9     115027.946103
10     81158.853683
11    112022.062063
Name: yhat, dtype: float64
Product: 2
0     8514.439097
1     8211.474618
2     7908.510136
3    17932.890591
4    12825.029513
5    12522.065033
6    12219.100556
7     9594.311587
8    11626.343969
Name: yhat, dtype: float64

10:44:49 - cmdstanpy - INFO - Chain [1] done processing
10:44:49 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing

Product: 3
0     9575.678566
1    65725.997669
2    70152.393675
3    74578.789690
4    60482.803058
5    83239.129703
Name: yhat, dtype: float64
Product: 4
0    26768.705301
1    33669.711009
2    74852.625691
3    47171.678610
Name: yhat, dtype: float64
Product: 5
0     13476.725938
1     13077.939159
2     12767.891976
3     15151.894177
4     14753.107399
5     14354.320621
6     15004.423302
7     10791.296640
8     10392.509861
9      9993.723083
10     9523.535266
11     9213.488082
Name: yhat, dtype: float64

10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing

Product: 6
0     27777.481571
1     26496.349644
2     36566.702190
3     37145.547134
4     35864.415203
5     34583.283270
6     32665.069751
7     30216.743919
8     28935.611986
9     27654.480053
10    15077.565033
11    25147.917575
Name: yhat, dtype: float64
Product: 7
0     105186.689585
1     108431.260608
2     154120.004706
3     196681.075607
4     199925.646573
5     203170.217556
6     204721.535046
7     170201.738777
8     173446.282967
9     176690.827157
10    137350.130440
11    183038.848398
Name: yhat, dtype: float64
Product: 8
0    -300.377389
1     433.682572
2    1167.742534
3    2713.803501
4    4001.154822
5    4735.214788
6    5469.274754
7    8064.254621
8    6905.479036
Name: yhat, dtype: float64

10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing

Product: 9
0     4176.873280
1     4252.041063
2     5292.952887
3     6843.841295
4     6919.009078
5     6994.176860
6     7100.888064
7     5665.523635
8     5740.691418
9     5815.859201
10    4922.014777
11    5962.926602
Name: yhat, dtype: float64
Product: 10
0     221.852417
1    2041.649939
2    3643.207363
3    5244.764784
4    5015.960215
5    8378.246697
Name: yhat, dtype: float64
Product: 11
0      58648.030453
1      59425.975063
2     133780.573516
3     193113.192304
4     193891.136914
5     194669.081525
6     245455.645890
7     137636.472884
8     138414.417488
9     139192.362093
10     66359.829178
11    140714.427625
Name: yhat, dtype: float64

10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing

Product: 12
0      14.997071
1     345.646552
2    1502.486186
3    2659.325819
4    2841.048298
5    4922.707710
Name: yhat, dtype: float64
Product: 13
0      4489.096779
1      4852.638041
2      8843.940992
3     17354.244639
4     17717.785901
5     18081.327163
6     15171.817095
7     10645.841161
8     11009.382423
9     11372.923685
10     8092.897117
11    12084.200067
Name: yhat, dtype: float64
Product: 14
0     1159.694227
1     1191.848328
2     1432.606225
3     2253.870416
4     2286.024517
5     2318.178618
6     2340.971575
7     1591.978724
8     1624.132825
9     1656.286926
10    1478.439226
11    1719.197123
Name: yhat, dtype: float64
Product: 15
0     -429.537987
1      -24.916564
2     1003.628218
3      848.239000
4     1252.860440
5     1657.481898
6     4320.642490
7     3009.143225
8     3413.764640
9     3818.386055
10    3581.491843
11    4610.036650
Name: yhat, dtype: float64

10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:50 - cmdstanpy - INFO - Chain [1] done processing
10:44:50 - cmdstanpy - INFO - Chain [1] start processing
10:44:51 - cmdstanpy - INFO - Chain [1] done processing
10:44:51 - cmdstanpy - INFO - Chain [1] start processing
10:44:51 - cmdstanpy - INFO - Chain [1] done processing
10:44:51 - cmdstanpy - INFO - Chain [1] start processing

Product: 16
0      5604.329584
1      5605.166732
2      7924.655992
3     10014.830025
4     10015.667171
5     10016.504317
6     14987.750181
7      7928.805326
8      7929.642473
9      7930.479619
10     5612.628255
11     7932.117515
Name: yhat, dtype: float64
Product: 17
0    13259.939654
1    21666.935218
2    30498.080210
3    38115.404802
Name: yhat, dtype: float64
Product: 18
0     1227.028338
1    24186.027375
2     7679.973523
3    69069.576383
Name: yhat, dtype: float64

10:44:51 - cmdstanpy - INFO - Chain [1] done processing

Product: 19
0     23824.363339
1     24111.540928
2     30245.537912
3     37579.411515
4     37866.589107
5     38153.766699
6     45969.294421
7     31668.939896
8     31956.117493
9     32243.295089
10    26671.167310
11    32805.164301
Name: yhat, dtype: float64