In [6]:
# Actual Value of Products sold 
Router1_data = [906, 941, 663, 769, 3565, 1020, 1670, 38, 2141]

#Prediction data using various methods

q1_pred = [
    {
        'type': 'Demand Planning',
        'accuracy': 0.71,
        'bias': -0.292
    },
    {
        'type': 'Marketing',
        'accuracy': 0.57,
        'bias': -0.427
    },
    {
        'type': 'ML',
        'accuracy': 0.50,
        'bias': -0.496
    }
]
q2_pred = [
    {
        'type': 'Demand Planning',
        'accuracy': 0,
        'bias': 58.684
    },
    {
        'type': 'Marketing',
        'accuracy': 0,
        'bias': 80.658 
    },
    {
        'type': 'ML',
        'accuracy': 0,
        'bias': 47.053
    }
]
q3_pred = [
    {
        'type': 'Demand Planning',
        'accuracy': 0.98,
        'bias': 0.025
    },
    {
        'type': 'Marketing',
        'accuracy': 0.72,
        'bias': 0.281
    },
    {
        'type': 'ML',
        'accuracy': 0.98,
        'bias': 0.016
    }
]

# Quarter 4 Prediction

q4_pred = {
    1716, 1716, 1948
}

In [7]:
# Finding actual prediction value for the methods

for type in q1_pred:
    type['prediction'] = ((type['bias'] / 100) * Router1_data[-3]) + Router1_data[-3] 
for type in q2_pred:
    type['prediction'] = ((type['bias'] / 100) * Router1_data[-2]) + Router1_data[-2] 
for type in q3_pred:
    type['prediction'] = ((type['bias'] / 100) * Router1_data[-1]) + Router1_data[-1] 
print(q1_pred)
print(q2_pred)
print(q3_pred)

[{'type': 'Demand Planning', 'accuracy': 0.71, 'bias': -0.292, 'prediction': 1665.1236}, {'type': 'Marketing', 'accuracy': 0.57, 'bias': -0.427, 'prediction': 1662.8691}, {'type': 'ML', 'accuracy': 0.5, 'bias': -0.496, 'prediction': 1661.7168}]
[{'type': 'Demand Planning', 'accuracy': 0, 'bias': 58.684, 'prediction': 60.29992}, {'type': 'Marketing', 'accuracy': 0, 'bias': 80.658, 'prediction': 68.65003999999999}, {'type': 'ML', 'accuracy': 0, 'bias': 47.053, 'prediction': 55.88014}]
[{'type': 'Demand Planning', 'accuracy': 0.98, 'bias': 0.025, 'prediction': 2141.53525}, {'type': 'Marketing', 'accuracy': 0.72, 'bias': 0.281, 'prediction': 2147.01621}, {'type': 'ML', 'accuracy': 0.98, 'bias': 0.016, 'prediction': 2141.34256}]

In [19]:
import pandas as pd
from prophet import Prophet

In [43]:
df = pd.read_csv('forcast.csv')
# df = df.T
df = df.T.reset_index()
# df = df.set_index(df.iloc[0])
df = df.drop(df.index[0])
df

         index       0         1        2  ...       16     17     18       19
1   2020-10-01     NaN   87173.0      NaN  ...   6187.0    NaN    NaN  28279.0
2   2021-01-01     NaN  102849.0      NaN  ...   5301.0    NaN    NaN  22704.0
3   2021-04-01     NaN  126375.0      NaN  ...   7172.0    NaN    NaN  24098.0
4   2021-07-01   906.0  128629.0   3651.0  ...   7582.0    NaN    NaN  31461.0
5   2021-10-01   941.0  179125.0  10409.0  ...  10964.0    NaN    NaN  47009.0
6   2022-01-01   663.0  138750.0  10575.0  ...  11501.0    NaN    NaN  35145.0
7   2022-04-01   769.0  208760.0  17934.0  ...  14980.0    NaN    NaN  45978.0
8   2022-07-01  3565.0  116126.0  15104.0  ...   9158.0    NaN    NaN  34518.0
9   2022-10-01    1020    150803    15525  ...    11601  13260   1227    40605
10  2023-01-01    1670     82163     6938  ...     3788  21667  24186    26925
11  2023-04-01      38     82408     9595  ...     5338  30498   7680    23635
12  2023-07-01    2141     67132     9231  ...     5595  40505  16772    17799

[12 rows x 21 columns]

In [45]:
router1 = pd.DataFrame()
router1 = df[['index', 0]].rename(columns={'index': 'ds', 0: 'y'})
router1

            ds       y
1   2020-10-01     NaN
2   2021-01-01     NaN
3   2021-04-01     NaN
4   2021-07-01   906.0
5   2021-10-01   941.0
6   2022-01-01   663.0
7   2022-04-01   769.0
8   2022-07-01  3565.0
9   2022-10-01    1020
10  2023-01-01    1670
11  2023-04-01      38
12  2023-07-01    2141

In [47]:
router1 = pd.DataFrame()
router1 = df[['index', 0]].rename(columns={'index': 'ds', 0: 'y'})
model.fit(router1)

11:10:16 - cmdstanpy - INFO - Chain [1] start processing
11:10:16 - cmdstanpy - INFO - Chain [1] done processing

In [54]:
for i in range(0,20):
    model = Prophet(weekly_seasonality=False, yearly_seasonality=False)
    model.add_seasonality(name='quarterly', period=4, fourier_order=5)
    router1 = pd.DataFrame()
    router1 = df[['index', i]].rename(columns={'index': 'ds', i: 'y'})
    model.fit(router1)
    future = model.make_future_dataframe(periods=1, freq='QE')  # Choose the number of steps to forecast
    forecast = model.predict(future)
    print("Product:", i)
    print(forecast)

11:17:26 - cmdstanpy - INFO - Chain [1] start processing

11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing

Product: 0
          ds       trend  ...  multiplicative_terms_upper         yhat
0 2021-07-01  149.098639  ...                         0.0   758.858734
1 2021-10-01  226.047689  ...                         0.0   835.807784
2 2022-01-01  302.996739  ...                         0.0   912.756834
3 2022-04-01  378.272984  ...                         0.0  1263.136999
4 2022-07-01  454.385631  ...                         0.0  2009.514565
5 2022-10-01  531.334681  ...                         0.0  2086.463615
6 2023-01-01  608.283731  ...                         0.0  2163.412665
7 2023-04-01  683.559975  ...                         0.0    30.813110
8 2023-07-01  759.672623  ...                         0.0  1644.536638
9 2023-09-30  835.785270  ...                         0.0  2390.914205

[10 rows x 16 columns]
Product: 1
           ds         trend  ...  multiplicative_terms_upper           yhat
0  2020-10-01  30184.399640  ...                         0.0  108202.938376
1  2021-01-01  25403.197875  ...                         0.0  103421.736611
2  2021-04-01  20725.935259  ...                         0.0  140227.340603
3  2021-07-01  15996.703003  ...                         0.0  153613.639377
4  2021-10-01  11215.501182  ...                         0.0  148832.437557
5  2022-01-01   6434.299321  ...                         0.0  144051.235696
6  2022-04-01   1757.036640  ...                         0.0  149788.495865
7  2022-07-01  -2972.195661  ...                         0.0  116529.209683
8  2022-10-01  -7753.397535  ...                         0.0  111748.007809
9  2023-01-01 -12534.599364  ...                         0.0  106966.805980
10 2023-04-01 -17211.862023  ...                         0.0   60806.676713
11 2023-07-01 -21941.094266  ...                         0.0  126090.364959
12 2023-09-30 -26670.326510  ...                         0.0   92831.078834

[13 rows x 16 columns]
Product: 2
          ds        trend  ...  multiplicative_terms_upper          yhat
0 2021-07-01  3488.647218  ...                         0.0   9604.876512
1 2021-10-01  2095.267201  ...                         0.0   8211.496495
2 2022-01-01   701.887184  ...                         0.0   6818.116478
3 2022-04-01  -661.201964  ...                         0.0  17035.046998
4 2022-07-01 -2039.436546  ...                         0.0  13915.327221
5 2022-10-01 -3432.816563  ...                         0.0  12521.947204
6 2023-01-01 -4826.196580  ...                         0.0  11128.567187
7 2023-04-01 -6189.285727  ...                         0.0   9593.822042
8 2023-07-01 -7567.520309  ...                         0.0  10128.728653
9 2023-09-30 -8945.754891  ...                         0.0   7009.008876

[10 rows x 16 columns]
Product: 3
          ds         trend  ...  multiplicative_terms_upper           yhat
0 2022-04-01   4098.386359  ...                         0.0   11808.732499
1 2022-07-01  13807.986092  ...                         0.0   60508.527644
2 2022-10-01  23624.284713  ...                         0.0   70324.826265
3 2023-01-01  33440.583339  ...                         0.0   80141.124890
4 2023-04-01  43043.484173  ...                         0.0   60507.207485
5 2023-07-01  52753.083906  ...                         0.0   60463.430046
6 2023-09-30  62462.683639  ...                         0.0  109163.225191

[7 rows x 16 columns]

11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing

Product: 4
          ds         trend  ...  multiplicative_terms_upper          yhat
0 2022-10-01  47286.027808  ...                         0.0  26768.747410
1 2023-01-01  54187.019122  ...                         0.0  33669.738727
2 2023-04-01  55117.706118  ...                         0.0  74853.067475
3 2023-07-01  47970.620731  ...                         0.0  80943.644792
4 2023-09-30  40823.535345  ...                         0.0  20306.254948

[5 rows x 16 columns]
Product: 5
           ds        trend  ...  multiplicative_terms_upper          yhat
0  2020-10-01  3070.374957  ...                         0.0  13858.668269
1  2021-01-01  2566.837535  ...                         0.0  13355.130847
2  2021-04-01  2074.246579  ...                         0.0  13237.233698
3  2021-07-01  1576.182390  ...                         0.0  15265.107353
4  2021-10-01  1072.644969  ...                         0.0  14761.569931
5  2022-01-01   569.107547  ...                         0.0  14258.032509
6  2022-04-01    76.489588  ...                         0.0  13078.234851
7  2022-07-01  -421.601904  ...                         0.0  10741.385216
8  2022-10-01  -925.166929  ...                         0.0  10237.820190
9  2023-01-01 -1428.731954  ...                         0.0   9734.255165
10 2023-04-01 -1921.349914  ...                         0.0   8866.943398
11 2023-07-01 -2419.441407  ...                         0.0  10582.303856
12 2023-09-30 -2917.532900  ...                         0.0   8245.454219

[13 rows x 16 columns]
Product: 6
           ds         trend  ...  multiplicative_terms_upper          yhat
0  2020-10-01   7433.665488  ...                         0.0  29157.673156
1  2021-01-01   5779.605379  ...                         0.0  27503.613046
2  2021-04-01   4161.503098  ...                         0.0  38249.755744
3  2021-07-01   2525.421902  ...                         0.0  37510.954270
4  2021-10-01    871.361790  ...                         0.0  35856.894159
5  2022-01-01   -782.698321  ...                         0.0  34202.834048
6  2022-04-01  -2400.800603  ...                         0.0  25734.687643
7  2022-07-01  -4036.881799  ...                         0.0  30051.370847
8  2022-10-01  -5690.941909  ...                         0.0  28397.310737
9  2023-01-01  -7345.002018  ...                         0.0  26743.250628
10 2023-04-01  -8963.104299  ...                         0.0  12760.903368
11 2023-07-01 -10599.185494  ...                         0.0  17536.302752
12 2023-09-30 -12235.266689  ...                         0.0  21852.985957

[13 rows x 16 columns]
Product: 7
           ds         trend  ...  multiplicative_terms_upper           yhat
0  2020-10-01  31441.368690  ...                         0.0  115808.038585
1  2021-01-01  31770.207981  ...                         0.0  116136.877876
2  2021-04-01  32091.898568  ...                         0.0  167265.078664
3  2021-07-01  32417.163478  ...                         0.0  199789.751950
4  2021-10-01  32746.002728  ...                         0.0  200118.591199
5  2022-01-01  33074.841991  ...                         0.0  200447.430463
6  2022-04-01  33396.532586  ...                         0.0  151822.139770
7  2022-07-01  33721.797342  ...                         0.0  168894.977438
8  2022-10-01  34050.636437  ...                         0.0  169223.816533
9  2023-01-01  34379.475555  ...                         0.0  169552.655652
10 2023-04-01  34701.165997  ...                         0.0  119067.835892
11 2023-07-01  35026.430777  ...                         0.0  153452.037962
12 2023-09-30  35351.695557  ...                         0.0  170524.875654

[13 rows x 16 columns]
Product: 8
          ds        trend  ...  multiplicative_terms_upper         yhat
0 2021-07-01   667.026188  ...                         0.0   280.460973
1 2021-10-01   818.933815  ...                         0.0   432.368600
2 2022-01-01   970.841442  ...                         0.0   584.276227
3 2022-04-01  1119.446730  ...                         0.0  2249.291537
4 2022-07-01  1269.703187  ...                         0.0  4581.653004
5 2022-10-01  1421.610815  ...                         0.0  4733.560632
6 2023-01-01  1573.518443  ...                         0.0  4885.468260
7 2023-04-01  1722.123731  ...                         0.0  8062.487970
8 2023-07-01  1872.380188  ...                         0.0  3002.224996
9 2023-09-30  2022.636646  ...                         0.0  5334.586463

[10 rows x 16 columns]

11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing
11:17:26 - cmdstanpy - INFO - Chain [1] start processing
11:17:26 - cmdstanpy - INFO - Chain [1] done processing

Product: 9
           ds        trend  ...  multiplicative_terms_upper         yhat
0  2020-10-01  1122.660998  ...                         0.0  4447.068323
1  2021-01-01  1123.565318  ...                         0.0  4447.972643
2  2021-04-01  1124.449979  ...                         0.0  5623.703956
3  2021-07-01  1125.344469  ...                         0.0  6915.954225
4  2021-10-01  1126.248789  ...                         0.0  6916.858545
5  2022-01-01  1127.153109  ...                         0.0  6917.762864
6  2022-04-01  1128.037769  ...                         0.0  5746.412207
7  2022-07-01  1128.932260  ...                         0.0  5628.186237
8  2022-10-01  1129.836579  ...                         0.0  5629.090557
9  2023-01-01  1130.740899  ...                         0.0  5629.994876
10 2023-04-01  1131.625559  ...                         0.0  4456.032884
11 2023-07-01  1132.520049  ...                         0.0  5750.894487
12 2023-09-30  1133.414539  ...                         0.0  5632.668517

[13 rows x 16 columns]
Product: 10
          ds        trend  ...  multiplicative_terms_upper         yhat
0 2022-04-01    42.041226  ...                         0.0   115.882025
1 2022-07-01  1367.355877  ...                         0.0  2298.882380
2 2022-10-01  2707.234425  ...                         0.0  3638.760928
3 2023-01-01  4047.112974  ...                         0.0  4978.639476
4 2023-04-01  5357.863727  ...                         0.0  5013.958191
5 2023-07-01  6683.178378  ...                         0.0  6757.019176
6 2023-09-30  8008.493029  ...                         0.0  8940.019531

[7 rows x 16 columns]
Product: 11
           ds         trend  ...  multiplicative_terms_upper           yhat
0  2020-10-01  31535.295885  ...                         0.0   75843.769245
1  2021-01-01  27586.435155  ...                         0.0   71894.908515
2  2021-04-01  23723.419208  ...                         0.0  154951.717056
3  2021-07-01  19817.480845  ...                         0.0  197927.096634
4  2021-10-01  15868.620083  ...                         0.0  193978.235872
5  2022-01-01  11919.759331  ...                         0.0  190029.375120
6  2022-04-01   8056.743381  ...                         0.0  159283.819111
7  2022-07-01   4150.805032  ...                         0.0  135379.102879
8  2022-10-01    201.944264  ...                         0.0  131430.242112
9  2023-01-01  -3746.916519  ...                         0.0  127481.381329
10 2023-04-01  -7609.932502  ...                         0.0   36698.540858
11 2023-07-01 -11515.870886  ...                         0.0  139711.204845
12 2023-09-30 -15421.809269  ...                         0.0  115806.488579

[13 rows x 16 columns]
Product: 12
          ds        trend  ...  multiplicative_terms_upper         yhat
0 2022-04-01    54.546632  ...                         0.0  -238.992307
1 2022-07-01   571.241813  ...                         0.0   978.783547
2 2022-10-01  1093.614960  ...                         0.0  1501.156694
3 2023-01-01  1615.988094  ...                         0.0  2023.529828
4 2023-04-01  2127.005297  ...                         0.0  2839.084048
5 2023-07-01  2643.700468  ...                         0.0  2350.161530
6 2023-09-30  3160.395639  ...                         0.0  3567.937373

[7 rows x 16 columns]

11:17:27 - cmdstanpy - INFO - Chain [1] start processing
11:17:27 - cmdstanpy - INFO - Chain [1] done processing
11:17:27 - cmdstanpy - INFO - Chain [1] start processing
11:17:27 - cmdstanpy - INFO - Chain [1] done processing
11:17:27 - cmdstanpy - INFO - Chain [1] start processing
11:17:27 - cmdstanpy - INFO - Chain [1] done processing
11:17:27 - cmdstanpy - INFO - Chain [1] start processing
11:17:27 - cmdstanpy - INFO - Chain [1] done processing

Product: 13
           ds        trend  ...  multiplicative_terms_upper          yhat
0  2020-10-01  2125.093329  ...                         0.0   5379.612903
1  2021-01-01  2240.838476  ...                         0.0   5495.358050
2  2021-04-01  2354.067426  ...                         0.0   9935.938452
3  2021-07-01  2468.554477  ...                         0.0  17591.783119
4  2021-10-01  2584.299627  ...                         0.0  17707.528269
5  2022-01-01  2699.499014  ...                         0.0  17822.727656
6  2022-04-01  2812.194068  ...                         0.0  10653.199466
7  2022-07-01  2926.141288  ...                         0.0  10508.012314
8  2022-10-01  3041.340673  ...                         0.0  10623.211699
9  2023-01-01  3156.540058  ...                         0.0  10738.411084
10 2023-04-01  3269.235108  ...                         0.0   6523.754682
11 2023-07-01  3383.182326  ...                         0.0  11224.187724
12 2023-09-30  3497.129544  ...                         0.0  11079.000570

[13 rows x 16 columns]
Product: 14
           ds       trend  ...  multiplicative_terms_upper         yhat
0  2020-10-01  344.379904  ...                         0.0  1264.257678
1  2021-01-01  347.808919  ...                         0.0  1267.686693
2  2021-04-01  351.163390  ...                         0.0  1561.027819
3  2021-07-01  354.555132  ...                         0.0  2282.635311
4  2021-10-01  357.984147  ...                         0.0  2286.064326
5  2022-01-01  361.413162  ...                         0.0  2289.493340
6  2022-04-01  364.767633  ...                         0.0  1817.460850
7  2022-07-01  368.159376  ...                         0.0  1578.023805
8  2022-10-01  371.588391  ...                         0.0  1581.452820
9  2023-01-01  375.017405  ...                         0.0  1584.881835
10 2023-04-01  378.371876  ...                         0.0  1298.249651
11 2023-07-01  381.763619  ...                         0.0  1834.456837
12 2023-09-30  385.155362  ...                         0.0  1595.019792

[13 rows x 16 columns]
Product: 15
           ds        trend  ...  multiplicative_terms_upper         yhat
0  2020-10-01    73.971713  ...                         0.0  -121.604869
1  2021-01-01   393.851148  ...                         0.0   198.274566
2  2021-04-01   706.776682  ...                         0.0  1378.295685
3  2021-07-01  1023.179166  ...                         0.0   932.804376
4  2021-10-01  1343.058600  ...                         0.0  1252.683810
5  2022-01-01  1662.938035  ...                         0.0  1572.563245
6  2022-04-01  1975.863568  ...                         0.0  2769.811307
7  2022-07-01  2292.266053  ...                         0.0  2963.785056
8  2022-10-01  2612.145488  ...                         0.0  3283.664491
9  2023-01-01  2932.024923  ...                         0.0  3603.543926
10 2023-04-01  3244.950457  ...                         0.0  3049.373875
11 2023-07-01  3561.352941  ...                         0.0  4355.300680
12 2023-09-30  3877.755426  ...                         0.0  4549.274429

[13 rows x 16 columns]
Product: 16
           ds        trend  ...  multiplicative_terms_upper          yhat
0  2020-10-01  1931.401360  ...                         0.0   6432.714596
1  2021-01-01  1704.733200  ...                         0.0   6206.046436
2  2021-04-01  1482.992609  ...                         0.0   8941.261973
3  2021-07-01  1258.788233  ...                         0.0  10241.295067
4  2021-10-01  1032.120073  ...                         0.0  10014.626907
5  2022-01-01   805.451913  ...                         0.0   9787.958747
6  2022-04-01   583.711322  ...                         0.0  10848.796768
7  2022-07-01   359.506947  ...                         0.0   7817.776311
8  2022-10-01   132.838786  ...                         0.0   7591.108150
9  2023-01-01   -93.829374  ...                         0.0   7364.439990
10 2023-04-01  -315.569966  ...                         0.0   4185.743270
11 2023-07-01  -539.774343  ...                         0.0   9725.311103
12 2023-09-30  -763.978719  ...                         0.0   6694.290645

[13 rows x 16 columns]

11:17:27 - cmdstanpy - INFO - Chain [1] start processing
11:17:27 - cmdstanpy - INFO - Chain [1] done processing
11:17:27 - cmdstanpy - INFO - Chain [1] start processing
11:17:27 - cmdstanpy - INFO - Chain [1] done processing

Product: 17
          ds         trend  ...  multiplicative_terms_upper          yhat
0 2022-10-01 -50556.315750  ...                         0.0  13259.801860
1 2023-01-01 -42149.312790  ...                         0.0  21666.804820
2 2023-04-01 -33925.109923  ...                         0.0  30498.088527
3 2023-07-01 -25609.526786  ...                         0.0  40504.961988
4 2023-09-30 -17293.943649  ...                         0.0  46522.173961

[5 rows x 16 columns]
Product: 18
          ds         trend  ...  multiplicative_terms_upper          yhat
0 2022-10-01 -42466.988100  ...                         0.0   1226.931593
1 2023-01-01 -19507.989063  ...                         0.0  24185.930629
2 2023-04-01   2951.901301  ...                         0.0   7679.949885
3 2023-07-01  25661.346010  ...                         0.0  16772.144500
4 2023-09-30  48370.790718  ...                         0.0  92064.710410

[5 rows x 16 columns]
Product: 19
           ds        trend  ...  multiplicative_terms_upper          yhat
0  2020-10-01  6785.514105  ...                         0.0  26426.358498
1  2021-01-01  6358.418152  ...                         0.0  25999.262545
2  2021-04-01  5940.606895  ...                         0.0  33444.975781
3  2021-07-01  5518.153291  ...                         0.0  38298.934560
4  2021-10-01  5091.057339  ...                         0.0  37871.838609
5  2022-01-01  4663.961389  ...                         0.0  37444.742658
6  2022-04-01  4246.150130  ...                         0.0  32947.612603
7  2022-07-01  3823.696521  ...                         0.0  31328.065407
8  2022-10-01  3396.600565  ...                         0.0  30900.969450
9  2023-01-01  2969.504607  ...                         0.0  30473.873493
10 2023-04-01  2551.693344  ...                         0.0  22192.537737
11 2023-07-01  2129.239734  ...                         0.0  30830.702206
12 2023-09-30  1706.786123  ...                         0.0  29211.155009

[13 rows x 16 columns]