In [3]:
import pandas as pd
from prophet import Prophet

In [4]:
df = pd.read_csv('forcast.csv')
# df = df.T
df = df.T.reset_index()
# df = df.set_index(df.iloc[0])
df = df.drop(df.index[0])
# df = df.drop(df.index[11])
df

,index,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
1,2020-05-01,NaN,87173.0,NaN,NaN,NaN,13432.0,28585.0,115709.0,NaN,...,NaN,65048.0,NaN,6073.0,1208.0,4.0,6187.0,NaN,NaN,28279.0
2,2020-08-01,NaN,102849.0,NaN,NaN,NaN,12463.0,19686.0,98337.0,NaN,...,NaN,67810.0,NaN,5459.0,963.0,-4.0,5301.0,NaN,NaN,22704.0
3,2020-11-01,NaN,126375.0,NaN,NaN,NaN,13452.0,44724.0,147681.0,NaN,...,NaN,90928.0,NaN,6736.0,1698.0,36.0,7172.0,NaN,NaN,24098.0
4,2021-02-01,906.0,128629.0,3651.0,NaN,NaN,14581.0,37781.0,185327.0,177.0,...,NaN,148547.0,NaN,12213.0,1833.0,305.0,7582.0,NaN,NaN,31461.0
5,2021-05-01,941.0,179125.0,10409.0,NaN,NaN,15831.0,31905.0,194170.0,270.0,...,NaN,228945.0,NaN,13883.0,2423.0,1093.0,10964.0,NaN,NaN,47009.0
6,2021-08-01,663.0,138750.0,10575.0,NaN,NaN,13864.0,37888.0,220386.0,850.0,...,NaN,204184.0,NaN,27045.0,2602.0,2360.0,11501.0,NaN,NaN,35145.0
7,2021-11-01,769.0,208760.0,17934.0,9576.0,NaN,15012.0,32689.0,204604.0,2717.0,...,222.0,245453.0,15.0,15162.0,2341.0,4317.0,14980.0,NaN,NaN,45978.0
8,2022-02-01,3565.0,116126.0,15104.0,46029.0,NaN,11349.0,30442.0,194538.0,3833.0,...,1549.0,245803.0,108.0,13855.0,1830.0,4343.0,9158.0,NaN,NaN,34518.0
9,2022-05-01,1020,150803,15525,109452,26769,10422,27028,185160,4279,...,4619,136283,1972,12351,1567,4094,11601,13260,1227,40605
10,2022-08-01,1670,82163,6938,54955,33670,8726,21246,147284,6089,...,4764,76020,2427,8933,1210,2756,3788,21667,24186,26925
11,2022-11-01,38,82408,9595,60478,74853,10185,21149,136997,8063,...,5015,51586,2841,5909,1659,3126,5338,30498,7680,23635

In [9]:
temp = result = pd.DataFrame({
    "product": [],
    "prediction": []
})
for i in range(0,20):
    model = Prophet(seasonality_mode='additive', yearly_seasonality=False, weekly_seasonality=False, daily_seasonality=False)
    model.add_seasonality(name='quarterly', period=4, fourier_order=6)
    router1 = pd.DataFrame()
    router1 = df[['index', i]].rename(columns={'index': 'ds', i: 'y'})
    model.fit(router1)
    future = model.make_future_dataframe(periods=1, freq='Q')  
    forecast = model.predict(future)
    print("Product:", i)
    # display(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(1))
    new_result = {"product": ("product0"+str(i)), "prediction": forecast[['yhat']].tail(1)}
    result = pd.concat([result, pd.DataFrame([new_result])], ignore_index=True)
    # fig = model.plot_components(forecast)
    # fig.show()
    forecast.to_csv('forcasts/product_'+str(i)+'.csv')
result.to_csv('results.csv')

18:12:55 - cmdstanpy - INFO - Chain [1] start processing

18:12:55 - cmdstanpy - INFO - Chain [1] done processing

Product: 0

          ds       yhat  yhat_lower   yhat_upper
8 2022-12-31  1606.3616  527.030609  2682.905353

AttributeError: 'DataFrame' object has no attribute 'append'